const express=require('express');
const Need=require('../models/Need'); const Giver=require('../models/Giver'); const Organization=require('../models/Organization'); const Interest=require('../models/Interest'); const Contribution=require('../models/Contribution'); const GiftOffering=require('../models/GiftOffering'); const User=require('../models/user');
const {Message,Notification,Category,SupportTicket,ActivityLog}=require('../models/Platform'); const {auth,roles}=require('../middleware/auth'); const {fail,ok,asyncRoute,parsePage,validId}=require('../utils/http'); const audit=require('../utils/audit');
const router=express.Router(); router.use(auth);
async function giverFor(userId){ return Giver.findOne({userId}); } async function orgFor(userId){ return Organization.findOne({userId}); }
function entityRoute(Model,name,{createRoles=[],updateRoles=[],deleteRoles=[]}={}){
 router.get(`/${name}`,asyncRoute(async(req,res)=>{ const {page,limit,skip}=parsePage(req); const q={}; if(req.query.status)q.status=req.query.status; if(req.query.category)q.category=req.query.category; const [items,total]=await Promise.all([Model.find(q).sort({createdAt:-1}).skip(skip).limit(limit).lean(),Model.countDocuments(q)]); return ok(res,{items,total,page,limit}); }));
 router.get(`/${name}/:id`,asyncRoute(async(req,res)=>{ if(!validId(req.params.id))return fail(res,400,'Invalid ID'); const item=await Model.findById(req.params.id).lean(); return item?ok(res,{item}):fail(res,404,`${name} not found`); }));
}
router.get('/needs',asyncRoute(async(req,res)=>{ const {page,limit,skip}=parsePage(req); const q={}; if(req.user.role==='giver')q.status={$in:['Open','In Progress']}; if(req.query.status)q.status=req.query.status; if(req.query.category)q.category=req.query.category; if(req.query.search)q.$text?null:q.title={$regex:String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),$options:'i'}; const [items,total]=await Promise.all([Need.find(q).populate('organizationId','name isVerified city province').sort({createdAt:-1}).skip(skip).limit(limit).lean(),Need.countDocuments(q)]); ok(res,{items,total,page,limit}); }));
router.post('/needs',roles('organization','admin'),asyncRoute(async(req,res)=>{ let organizationId=req.body.organizationId; if(req.user.role==='organization'){const o=await orgFor(req.user._id); if(!o)return fail(res,400,'Organization profile not found'); organizationId=o._id;} const need=await Need.create({...req.body,organizationId,status:req.user.role==='admin'?(req.body.status||'Open'):'Pending Approval'}); await audit(req,'CREATE_NEED','Need',need._id); ok(res,{message:'Need created successfully',item:need},201); }));
router.put('/needs/:id',roles('organization','admin'),asyncRoute(async(req,res)=>{ const need=await Need.findById(req.params.id); if(!need)return fail(res,404,'Need not found'); if(req.user.role==='organization'){const o=await orgFor(req.user._id); if(!o||String(need.organizationId)!==String(o._id))return fail(res,403,'You can only update your own needs'); const protectedFields=['status','approvalNote','organizationId']; protectedFields.forEach(k=>delete req.body[k]);} Object.assign(need,req.body); await need.save(); await audit(req,'UPDATE_NEED','Need',need._id); ok(res,{message:'Need updated successfully',item:need}); }));
router.delete('/needs/:id',roles('organization','admin'),asyncRoute(async(req,res)=>{ const need=await Need.findById(req.params.id); if(!need)return fail(res,404,'Need not found'); if(req.user.role==='organization'){const o=await orgFor(req.user._id); if(!o||String(need.organizationId)!==String(o._id))return fail(res,403,'You can only remove your own needs');} await need.deleteOne(); await audit(req,'DELETE_NEED','Need',need._id); ok(res,{message:'Need deleted successfully'}); }));
router.post('/needs/:id/approval',roles('admin'),asyncRoute(async(req,res)=>{ const status=req.body.action==='approve'?'Open':req.body.action==='reject'?'Rejected':null; if(!status)return fail(res,400,'Action must be approve or reject'); const item=await Need.findByIdAndUpdate(req.params.id,{status,approvalNote:req.body.note||''},{new:true,runValidators:true}); if(!item)return fail(res,404,'Need not found'); await audit(req,'REVIEW_NEED','Need',item._id,{status}); ok(res,{message:`Need ${status.toLowerCase()}`,item}); }));
router.post('/needs/:id/save',roles('giver'),asyncRoute(async(req,res)=>{ const g=await giverFor(req.user._id); if(!g)return fail(res,400,'Giver profile not found'); const saved=new Set((req.user.preferences?.savedNeedIds||[]).map(String)); const id=req.params.id; let savedNow; if(saved.has(id)){saved.delete(id);savedNow=false}else{saved.add(id);savedNow=true} req.user.preferences={...(req.user.preferences||{}),savedNeedIds:[...saved]}; req.user.markModified('preferences'); await req.user.save(); ok(res,{message:savedNow?'Need saved':'Need removed from saved list',saved:savedNow}); }));
router.post('/interests',roles('giver'),asyncRoute(async(req,res)=>{ const g=await giverFor(req.user._id); const need=await Need.findById(req.body.needId); if(!g||!need)return fail(res,404,'Giver profile or need not found'); const item=await Interest.create({...req.body,giverId:g._id,organizationId:need.organizationId}); await Notification.create({userId:(await Organization.findById(need.organizationId)).userId,title:'New giver interest',body:`A giver expressed interest in ${need.title}`,type:'interest'}); await audit(req,'CREATE_INTEREST','Interest',item._id); ok(res,{message:'Interest submitted successfully',item},201); }));
router.get('/interests',asyncRoute(async(req,res)=>{ const q={}; if(req.user.role==='giver'){const g=await giverFor(req.user._id);q.giverId=g?g._id:null;} else if(req.user.role==='organization'){const o=await orgFor(req.user._id);q.organizationId=o?o._id:null;} if(req.query.status)q.status=req.query.status; const items=await Interest.find(q).populate('needId','title category status').populate('giverId','name publicDisplayName email phone').sort({createdAt:-1}).lean(); ok(res,{items}); }));
router.put('/interests/:id/status',roles('organization','admin'),asyncRoute(async(req,res)=>{ const allowed=['Accepted','Declined','Completed','Cancelled']; if(!allowed.includes(req.body.status))return fail(res,400,'Invalid interest status'); const item=await Interest.findById(req.params.id); if(!item)return fail(res,404,'Interest not found'); if(req.user.role==='organization'){const o=await orgFor(req.user._id);if(!o||String(o._id)!==String(item.organizationId))return fail(res,403,'Not permitted');} item.status=req.body.status; await item.save(); await audit(req,'UPDATE_INTEREST','Interest',item._id,{status:item.status}); ok(res,{message:'Interest updated',item}); }));
router.post('/contributions',roles('giver'),asyncRoute(async(req,res)=>{ const g=await giverFor(req.user._id); const need=await Need.findById(req.body.needId); if(!g||!need)return fail(res,404,'Giver profile or need not found'); const item=await Contribution.create({...req.body,giverId:g._id,organizationId:need.organizationId}); await audit(req,'CREATE_CONTRIBUTION','Contribution',item._id); ok(res,{message:'Contribution recorded successfully',item},201); }));
router.get('/contributions',asyncRoute(async(req,res)=>{ const q={}; if(req.user.role==='giver'){const g=await giverFor(req.user._id);q.giverId=g?g._id:null;} if(req.user.role==='organization'){const o=await orgFor(req.user._id);q.organizationId=o?o._id:null;} const items=await Contribution.find(q).populate('needId','title').sort({createdAt:-1}).lean(); ok(res,{items}); }));
router.put('/contributions/:id/status',roles('organization','admin'),asyncRoute(async(req,res)=>{ const allowed=['Pending','Confirmed','In Progress','Completed','Cancelled']; if(!allowed.includes(req.body.status))return fail(res,400,'Invalid contribution status'); const item=await Contribution.findByIdAndUpdate(req.params.id,{status:req.body.status,receiptNumber:req.body.receiptNumber,receiptUrl:req.body.receiptUrl},{new:true,runValidators:true}); if(!item)return fail(res,404,'Contribution not found'); ok(res,{message:'Contribution updated',item}); }));
router.post('/gift-offerings',roles('giver'),asyncRoute(async(req,res)=>{ const g=await giverFor(req.user._id); if(!g)return fail(res,400,'Giver profile not found'); const item=await GiftOffering.create({...req.body,giverId:g._id,status:'Pending Approval'}); await audit(req,'CREATE_GIFT','GiftOffering',item._id); ok(res,{message:'Gift offering submitted for approval',item},201); }));
router.get('/gift-offerings',asyncRoute(async(req,res)=>{ const q={}; if(req.user.role==='giver'){const g=await giverFor(req.user._id);q.giverId=g?g._id:null;} else if(req.user.role==='organization')q.status={$in:['Available','Matched']}; if(req.query.status)q.status=req.query.status; const items=await GiftOffering.find(q).populate('giverId','name publicDisplayName').populate('matchedNeedId','title').sort({createdAt:-1}).lean(); ok(res,{items}); }));
router.put('/gift-offerings/:id',roles('giver','admin'),asyncRoute(async(req,res)=>{ const item=await GiftOffering.findById(req.params.id); if(!item)return fail(res,404,'Gift offering not found'); if(req.user.role==='giver'){const g=await giverFor(req.user._id);if(!g||String(g._id)!==String(item.giverId))return fail(res,403,'Not permitted'); ['status','giverId','matchedNeedId','matchedOrganizationId'].forEach(k=>delete req.body[k]);} Object.assign(item,req.body);await item.save();ok(res,{message:'Gift offering updated',item}); }));
router.post('/gift-offerings/:id/approval',roles('admin'),asyncRoute(async(req,res)=>{ const status=req.body.action==='approve'?'Available':req.body.action==='reject'?'Rejected':null;if(!status)return fail(res,400,'Action must be approve or reject');const item=await GiftOffering.findByIdAndUpdate(req.params.id,{status},{new:true});if(!item)return fail(res,404,'Gift offering not found');ok(res,{message:`Gift offering ${status.toLowerCase()}`,item}); }));
router.post('/gift-offerings/:id/match',roles('organization','admin'),asyncRoute(async(req,res)=>{ const o=req.user.role==='organization'?await orgFor(req.user._id):await Organization.findById(req.body.organizationId); const need=await Need.findById(req.body.needId); if(!o||!need||String(need.organizationId)!==String(o._id))return fail(res,400,'Valid organization need is required'); const item=await GiftOffering.findOneAndUpdate({_id:req.params.id,status:'Available'},{status:'Matched',matchedNeedId:need._id,matchedOrganizationId:o._id},{new:true}); if(!item)return fail(res,409,'Gift offering is no longer available');ok(res,{message:'Gift offering matched successfully',item}); }));
router.get('/messages',asyncRoute(async(req,res)=>{ const items=await Message.find({$or:[{senderUserId:req.user._id},{recipientUserId:req.user._id}]}).sort({createdAt:-1}).lean(); ok(res,{items}); }));
router.post('/messages',asyncRoute(async(req,res)=>{ if(!validId(req.body.recipientUserId)||!req.body.body)return fail(res,400,'Recipient and message body are required'); const item=await Message.create({...req.body,senderUserId:req.user._id}); await Notification.create({userId:req.body.recipientUserId,type:'message',title:req.body.subject||'New message',body:String(req.body.body).slice(0,180)}); ok(res,{message:'Message sent',item},201); }));
router.post('/messages/:id/read',asyncRoute(async(req,res)=>{ const item=await Message.findOneAndUpdate({_id:req.params.id,recipientUserId:req.user._id},{readAt:new Date()},{new:true}); item?ok(res,{item}):fail(res,404,'Message not found'); }));
router.get('/notifications',asyncRoute(async(req,res)=>{ const items=await Notification.find({userId:req.user._id}).sort({createdAt:-1}).limit(100).lean(); ok(res,{items}); }));
router.post('/notifications/:id/read',asyncRoute(async(req,res)=>{ const item=await Notification.findOneAndUpdate({_id:req.params.id,userId:req.user._id},{readAt:new Date()},{new:true}); item?ok(res,{item}):fail(res,404,'Notification not found'); }));
router.post('/notifications/read-all',asyncRoute(async(req,res)=>{ await Notification.updateMany({userId:req.user._id,readAt:null},{readAt:new Date()}); ok(res,{message:'Notifications marked as read'}); }));
router.get('/categories',asyncRoute(async(req,res)=>ok(res,{items:await Category.find(req.user.role==='admin'?{}:{active:true}).sort({name:1}).lean()})));
router.post('/categories',roles('admin'),asyncRoute(async(req,res)=>{ if(!req.body.name)return fail(res,400,'Category name is required'); const item=await Category.create(req.body);ok(res,{message:'Category created',item},201); }));
router.put('/categories/:id',roles('admin'),asyncRoute(async(req,res)=>{ const item=await Category.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});item?ok(res,{message:'Category updated',item}):fail(res,404,'Category not found'); }));
router.delete('/categories/:id',roles('admin'),asyncRoute(async(req,res)=>{ const item=await Category.findByIdAndDelete(req.params.id);item?ok(res,{message:'Category deleted'}):fail(res,404,'Category not found'); }));
router.get('/tickets',asyncRoute(async(req,res)=>{ const q=req.user.role==='admin'?{}:{userId:req.user._id};ok(res,{items:await SupportTicket.find(q).sort({createdAt:-1}).lean()}); }));
router.post('/tickets',asyncRoute(async(req,res)=>{ if(!req.body.subject||!req.body.description)return fail(res,400,'Subject and description are required');const item=await SupportTicket.create({...req.body,userId:req.user._id});ok(res,{message:'Support ticket created',item},201); }));
router.put('/tickets/:id',roles('admin'),asyncRoute(async(req,res)=>{ const item=await SupportTicket.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});item?ok(res,{message:'Support ticket updated',item}):fail(res,404,'Support ticket not found'); }));
router.post('/tickets/:id/respond',asyncRoute(async(req,res)=>{ if(!req.body.body)return fail(res,400,'Response body is required');const q=req.user.role==='admin'?{_id:req.params.id}:{_id:req.params.id,userId:req.user._id};const item=await SupportTicket.findOneAndUpdate(q,{$push:{responses:{userId:req.user._id,body:req.body.body}}},{new:true});item?ok(res,{message:'Response added',item}):fail(res,404,'Support ticket not found'); }));
router.get('/admin/users',roles('admin'),asyncRoute(async(req,res)=>{ const items=await User.find().sort({createdAt:-1}).lean();ok(res,{items}); }));
router.put('/admin/users/:id/status',roles('admin'),asyncRoute(async(req,res)=>{ if(!['Active','Suspended','Pending'].includes(req.body.status))return fail(res,400,'Invalid user status');const item=await User.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true});item?ok(res,{message:'User status updated',item}):fail(res,404,'User not found'); }));
router.get('/admin/organizations',roles('admin'),asyncRoute(async(req,res)=>ok(res,{items:await Organization.find().populate('userId','status createdAt').sort({createdAt:-1}).lean()})));
router.post('/admin/organizations/:id/approval',roles('admin'),asyncRoute(async(req,res)=>{ const approved=req.body.action==='approve'; const rejected=req.body.action==='reject'; if(!approved&&!rejected)return fail(res,400,'Action must be approve or reject'); const item=await Organization.findByIdAndUpdate(req.params.id,{isVerified:approved,verificationStatus:approved?'Approved':'Rejected'},{new:true});item?ok(res,{message:`Organization ${approved?'approved':'rejected'}`,item}):fail(res,404,'Organization not found'); }));
router.get('/admin/activity',roles('admin'),asyncRoute(async(req,res)=>ok(res,{items:await ActivityLog.find().populate('userId','name email role').sort({createdAt:-1}).limit(250).lean()})));
router.get('/dashboard',asyncRoute(async(req,res)=>{ if(req.user.role==='giver'){const g=await giverFor(req.user._id); const saved=req.user.preferences?.savedNeedIds||[]; const [needs,interests,contributions,gifts,messages,notifications]=await Promise.all([Need.find({status:{$in:['Open','In Progress']}}).populate('organizationId','name isVerified city province').sort({createdAt:-1}).lean(),Interest.find({giverId:g?g._id:null}).populate('needId','title').sort({createdAt:-1}).lean(),Contribution.find({giverId:g?g._id:null}).populate('needId','title').sort({createdAt:-1}).lean(),GiftOffering.find({giverId:g?g._id:null}).sort({createdAt:-1}).lean(),Message.find({$or:[{senderUserId:req.user._id},{recipientUserId:req.user._id}]}).sort({createdAt:-1}).lean(),Notification.find({userId:req.user._id}).sort({createdAt:-1}).lean()]);return ok(res,{role:'giver',profile:g,needs,savedNeedIds:saved,interests,contributions,gifts,messages,notifications});}
 if(req.user.role==='organization'){const o=await orgFor(req.user._id);const [needs,interests,contributions,gifts,messages,notifications]=await Promise.all([Need.find({organizationId:o?o._id:null}).sort({createdAt:-1}).lean(),Interest.find({organizationId:o?o._id:null}).populate('giverId','name publicDisplayName').populate('needId','title').sort({createdAt:-1}).lean(),Contribution.find({organizationId:o?o._id:null}).populate('needId','title').sort({createdAt:-1}).lean(),GiftOffering.find({status:{$in:['Available','Matched']}}).sort({createdAt:-1}).lean(),Message.find({$or:[{senderUserId:req.user._id},{recipientUserId:req.user._id}]}).sort({createdAt:-1}).lean(),Notification.find({userId:req.user._id}).sort({createdAt:-1}).lean()]);return ok(res,{role:'organization',profile:o,needs,interests,contributions,gifts,messages,notifications});}
 const [users,organizations,needs,gifts,tickets,activity]=await Promise.all([User.find().lean(),Organization.find().lean(),Need.find().lean(),GiftOffering.find().lean(),SupportTicket.find().lean(),ActivityLog.find().sort({createdAt:-1}).limit(100).lean()]); return ok(res,{role:'admin',users,organizations,needs,gifts,tickets,activity}); }));
module.exports=router;
