const express=require("express"); const cors=require("cors"); const mongoose=require("mongoose"); require("dotenv").config();
const organizationRoutes=require("./routes/organizationRoutes"); const giverRoutes=require("./routes/giverRoutes"); const userRoutes=require("./routes/userRoutes"); const platformRoutes=require("./routes/platformRoutes");
const app=express(); const PORT=Number(process.env.PORT)||5000;
app.disable('x-powered-by'); app.use(cors({origin:(process.env.FRONTEND_URL||'http://localhost:3000').split(','),credentials:true})); app.use(express.json({limit:'2mb'}));
app.get('/health',(req,res)=>res.json({success:true,status:'ok',database:mongoose.connection.readyState===1?'connected':'disconnected',timestamp:new Date().toISOString()})); app.get('/',(req,res)=>res.send('HelpLift Backend is running!'));
app.use('/api/users',userRoutes); app.use('/api/platform',platformRoutes); app.use('/api/organizations',organizationRoutes); app.use('/api/givers',giverRoutes);
app.use((req,res)=>res.status(404).json({success:false,message:'Route not found'})); app.use((err,req,res,next)=>{console.error(err); if(err?.code===11000)return res.status(409).json({success:false,message:'A record with that unique value already exists',field:Object.keys(err.keyPattern||{})[0]}); if(err?.name==='ValidationError')return res.status(400).json({success:false,message:'Validation failed',details:Object.values(err.errors).map(e=>e.message)}); res.status(500).json({success:false,message:process.env.NODE_ENV==='production'?'Internal server error':err.message});});
async function start(){ if(!process.env.MONGO_URI){console.error('Missing MONGO_URI. Add it to Backend/.env before starting.');process.exit(1);} if(!process.env.JWT_SECRET)console.warn('WARNING: JWT_SECRET is not set; using development fallback.'); await mongoose.connect(process.env.MONGO_URI,{serverSelectionTimeoutMS:10000}); console.log('Connected to MongoDB'); app.listen(PORT,()=>console.log(`HelpLift server is running on port ${PORT}`)); }
start().catch(e=>{console.error('Startup failed:',e);process.exit(1)});
