const mongoose = require("mongoose");
const messageSchema = new mongoose.Schema({ senderUserId:{type:mongoose.Schema.Types.ObjectId,ref:"User",required:true,index:true}, recipientUserId:{type:mongoose.Schema.Types.ObjectId,ref:"User",required:true,index:true}, relatedNeedId:{type:mongoose.Schema.Types.ObjectId,ref:"Need"}, subject:{type:String,default:""}, body:{type:String,required:true}, readAt:Date },{timestamps:true});
const notificationSchema = new mongoose.Schema({ userId:{type:mongoose.Schema.Types.ObjectId,ref:"User",required:true,index:true}, type:{type:String,default:"general"}, title:{type:String,required:true}, body:{type:String,default:""}, link:{type:String,default:""}, readAt:Date },{timestamps:true});
const categorySchema = new mongoose.Schema({ name:{type:String,required:true,unique:true,trim:true}, description:{type:String,default:""}, active:{type:Boolean,default:true} },{timestamps:true});
const ticketSchema = new mongoose.Schema({ userId:{type:mongoose.Schema.Types.ObjectId,ref:"User",required:true,index:true}, subject:{type:String,required:true}, description:{type:String,required:true}, priority:{type:String,enum:["Low","Medium","High","Urgent"],default:"Medium"}, status:{type:String,enum:["Open","In Progress","Resolved","Closed"],default:"Open",index:true}, assignedTo:{type:mongoose.Schema.Types.ObjectId,ref:"User"}, responses:[{userId:{type:mongoose.Schema.Types.ObjectId,ref:"User"},body:String,createdAt:{type:Date,default:Date.now}}] },{timestamps:true});
const logSchema = new mongoose.Schema({ userId:{type:mongoose.Schema.Types.ObjectId,ref:"User"}, action:{type:String,required:true,index:true}, entityType:String, entityId:String, details:{type:mongoose.Schema.Types.Mixed,default:{}}, ip:String },{timestamps:true});
const sessionSchema = new mongoose.Schema({ userId:{type:mongoose.Schema.Types.ObjectId,ref:"User",required:true,index:true}, deviceId:{type:String,required:true}, deviceName:{type:String,default:"Browser"}, location:{type:String,default:"Unknown"}, tokenId:{type:String,required:true,unique:true}, revokedAt:Date, lastSeenAt:{type:Date,default:Date.now}, expiresAt:{type:Date,required:true,index:{expires:0}} },{timestamps:true});
module.exports={
 Message: mongoose.models.Message||mongoose.model("Message",messageSchema), Notification: mongoose.models.Notification||mongoose.model("Notification",notificationSchema),
 Category: mongoose.models.Category||mongoose.model("Category",categorySchema), SupportTicket: mongoose.models.SupportTicket||mongoose.model("SupportTicket",ticketSchema),
 ActivityLog: mongoose.models.ActivityLog||mongoose.model("ActivityLog",logSchema), Session: mongoose.models.Session||mongoose.model("Session",sessionSchema)
};
